### ISSUE TITLE
Standard defined as stories

### ISSUE THREAD

**Issue by derega** [educloudalliance/eca-docs#2]
It would be beneficial for all parties to understand the standard, or ECA architecture, from their point of view. For a student it is really hard to see the benefits of the standard if it is written from a developer point of view.

We know already many different actors and groups who would like to know what this standard does for them. We should write the text as clearly as possible for all parties to understand it in the language they are already familiar. 

When the people who are writing the standard need to think from different point of view it also makes them understand it better.

**Comment by kyyberi** [comment]
+1

**Comment by derega** [comment]
New idea: We now have a story about user freely choosing the material. Should we consider also group work and collaboration on this level or is it more in the implementation side?

**Comment by derega** [comment]
Created new issue from previous comment. This Issue can now be closed as the documentation is now story based. Story definitions at the moment are pretty thin, but work can continue in separate issues per story.
